spring:
  datasource:
    url: jdbc:mysql://localhost:3306/newtaskdb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  application:
    name: task
