server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vidur1996/spring-cloud-config-store
          search-paths:
            - 'service-config/*service'


